/**
 * Backend-agnostic physics types.
 *
 * ThreeDream does not marry one physics engine. `PhysicsBackend` is the only
 * surface gameplay code touches, so Rapier (WASM), a built-in solver, or a
 * future GPU backend can be swapped without rewriting scenes. All vectors are
 * plain number triples rather than `THREE.Vector3` to keep the physics layer
 * free of renderer imports and safe to run in a Worker or headless Node.
 */

export type Vec3 = readonly [number, number, number];

export function vec3(x = 0, y = 0, z = 0): Vec3 {
  return [x, y, z];
}

export function addVec3(a: Vec3, b: Vec3): Vec3 {
  return [a[0] + b[0], a[1] + b[1], a[2] + b[2]];
}

export function subVec3(a: Vec3, b: Vec3): Vec3 {
  return [a[0] - b[0], a[1] - b[1], a[2] - b[2]];
}

export function scaleVec3(a: Vec3, s: number): Vec3 {
  return [a[0] * s, a[1] * s, a[2] * s];
}

export function dotVec3(a: Vec3, b: Vec3): number {
  return a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
}

export function crossVec3(a: Vec3, b: Vec3): Vec3 {
  return [
    a[1] * b[2] - a[2] * b[1],
    a[2] * b[0] - a[0] * b[2],
    a[0] * b[1] - a[1] * b[0],
  ];
}

export function lengthVec3(a: Vec3): number {
  return Math.sqrt(dotVec3(a, a));
}

export function normalizeVec3(a: Vec3): Vec3 {
  const len = lengthVec3(a);
  return len > 1e-9 ? scaleVec3(a, 1 / len) : vec3();
}

export function distanceVec3(a: Vec3, b: Vec3): number {
  return lengthVec3(subVec3(a, b));
}

/** Unit vector along `axis` (0=x, 1=y, 2=z), scaled by `sign`. */
export function axisVec3(axis: number, sign = 1): Vec3 {
  const out: [number, number, number] = [0, 0, 0];
  out[axis] = sign;
  return out;
}

/** Quaternion as [x, y, z, w], the order Rapier and three.js both use. */
export type Quat = readonly [number, number, number, number];

export function quatFromEulerXYZ(euler: Vec3): Quat {
  const [x, y, z] = euler;
  const cx = Math.cos(x / 2);
  const sx = Math.sin(x / 2);
  const cy = Math.cos(y / 2);
  const sy = Math.sin(y / 2);
  const cz = Math.cos(z / 2);
  const sz = Math.sin(z / 2);
  return [
    sx * cy * cz + cx * sy * sz,
    cx * sy * cz - sx * cy * sz,
    cx * cy * sz + sx * sy * cz,
    cx * cy * cz - sx * sy * sz,
  ];
}

/**
 * Quaternion back to Euler XYZ radians, inverting `quatFromEulerXYZ`.
 *
 * The three `atan2`/`asin` terms must be the ones for the *same* rotation order
 * the forward function composes (q = qx·qy·qz). Using the ZYX forms instead
 * round-trips identity and single-axis rotations correctly and silently returns
 * wrong angles for every combined rotation, which is how this went unnoticed:
 * `rapier.ts` reads body rotation through here.
 */
export function eulerFromQuatXYZ(q: Quat): Vec3 {
  const [x, y, z, w] = q;
  const sinp = 2 * (w * y + x * z);
  const pitch =
    Math.abs(sinp) >= 1 ? (Math.sign(sinp) * Math.PI) / 2 : Math.asin(sinp);
  const roll = Math.atan2(2 * (w * x - y * z), 1 - 2 * (x * x + y * y));
  const yaw = Math.atan2(2 * (w * z - x * y), 1 - 2 * (y * y + z * z));
  return [roll, pitch, yaw];
}

export type BodyShape =
  | { kind: 'sphere'; radius: number }
  | { kind: 'box'; halfExtents: Vec3 }
  | { kind: 'capsule'; radius: number; halfHeight: number };

export type BodyKind = 'dynamic' | 'kinematic' | 'static';

export interface BodyDescriptor {
  shape: BodyShape;
  position: Vec3;
  /** Euler angles in radians, XYZ order. Rotation support is intentionally basic. */
  rotation?: Vec3;
  velocity?: Vec3;
  kind?: BodyKind;
  mass?: number;
  restitution?: number;
  friction?: number;
  /** Bitmask for cheap collision filtering; 0 collides with everything. */
  group?: number;
  mask?: number;
  /** Free-form label, surfaced in contact events and useful for rewards. */
  label?: string;
}

export interface BodyState {
  position: Vec3;
  rotation: Vec3;
  velocity: Vec3;
  angularVelocity: Vec3;
}

export interface ContactEvent {
  a: number;
  b: number;
  normal: Vec3;
  depth: number;
  impulse: number;
  labels: [string, string];
}

export interface RayHit {
  body: number;
  point: Vec3;
  normal: Vec3;
  distance: number;
}

export interface PhysicsBackend {
  readonly name: string;
  readonly deterministic: boolean;
  /** Fixed timestep the backend was configured with, in seconds. */
  readonly fixedDt: number;

  createBody(descriptor: BodyDescriptor): number;
  destroyBody(handle: number): void;
  getBodyState(handle: number): BodyState | undefined;
  setBodyState(handle: number, state: Partial<BodyState>): void;
  applyImpulse(handle: number, impulse: Vec3): void;
  applyForce(handle: number, force: Vec3): void;

  /** Advance exactly one fixed step. */
  step(dt: number): void;

  /** Contacts generated by the most recent step. */
  drainContacts(): ContactEvent[];

  raycast(origin: Vec3, direction: Vec3, maxDistance: number): RayHit | undefined;

  get bodyCount(): number;
  dispose(): void;
}

export interface PhysicsWorldOptions {
  gravity?: Vec3;
  fixedDt?: number;
  /** Iterations for the contact solve. More is stiffer, costs linear time. */
  solverIterations?: number;
  /** Linear velocity damping per second. */
  linearDamping?: number;
  angularDamping?: number;
}
